# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9499853556cfd3fd844515dc414fb61f36035c97732d9b8060a2db9369e29ca1593fdf34779ec6a7fa539aa8a7917362c969b218922e3285e8fe06ecf20b3e84

test:
  secret_key_base: e473dd2dae922ca5ff106176ef08f92957c0bcd7b5df718f71ed6b3e08f9007e439beb7cc5674b06de2f2999e8825a39070a1468c23960db7da9dac7957b1c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
